#!/usr/bin/env bash
# run CI-like set of tests
set -eu

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd "$dir"

echo "==> test"
cargo test
cargo test --benches
echo "==> no_std"
(cd rasterizer && cargo build --target thumbv6m-none-eabi --no-default-features --features libm)
(cd glyph && cargo build --target thumbv6m-none-eabi --no-default-features --features libm-math)
echo "==> rustfmt"
cargo fmt -- --check
